[package]
name = "rapier_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.3.21", features = ["derive"] }
renderer = { path = "libs/renderer" }
